[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "deprecated-parameters"
dynamic = ["version"]
description = "Deprecation of parameters in function and method signatures."
authors = [
    {name = "Mauricio Villegas", email = "mauricio@omnius.com"},
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"

dependencies = [
    "packaging>=22.0",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
]


[project.optional-dependencies]
mypy = [
    "mypy>=1.14.1",
]
doc = [
    "sphinx>=7.0.0",
]
test = [
    "deprecated-parameters[mypy,doc]",
    "pytest>=6.2.5",
    "pytest-cov>=4.0.0",
]
dev = [
    "pre-commit>=2.19.0",
    "tox>=3.25.0",
    "build>=0.10.0",
    "twine>=4.0.0",
    "bump2version>=1.0.1",
]

[project.scripts]
deprecated-parameters-stubgen = "deprecated_parameters._stubgen:main"

[project.urls]
GitHub = "https://github.com/mauvilsa/deprecated-parameters"
PyPI = "https://pypi.org/project/deprecated-parameters"
Changelog = "https://github.com/mauvilsa/deprecated-parameters/blob/main/CHANGELOG.md"


[tool.setuptools]
platforms = ["Any"]
packages = ["deprecated_parameters", "deprecated_parameters_tests"]

[tool.setuptools.dynamic]
version = {attr = "deprecated_parameters.__version__"}

[tool.setuptools.package-data]
deprecated_parameters = ["py.typed"]


[tool.pytest.ini_options]
addopts = "-s"
testpaths = ["deprecated_parameters_tests"]


[tool.coverage.run]
relative_files = true
source = ["deprecated_parameters"]


[tool.mypy]
warn_unused_ignores = true


[tool.ruff]
fix = true
line-length = 120

[tool.ruff.lint]
select = [
    "E", "W",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
]


[tool.typos.default.extend-identifiers]
Villegas = "Villegas"


[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{310,311,312,313,314}
skip_missing_interpreters = true

[testenv]
extras = test
changedir = deprecated_parameters_tests
commands = python -m pytest {posargs}
"""
