"""Generate ``@overload`` plus ``@deprecated`` stubs for the declared parameter deprecations.

The mypy plugin is the only way to report deprecated parameters in mypy, but pyright, ty and pyrefly have
no plugin system. What they do support is :pep:`702`, ``warnings.deprecated``, applied to an individual
``@overload``. This module renders the deprecations of a module as such overloads, so that those type
checkers report them too::

    deprecated-parameters-stubgen mypackage.mymodule -o overloads.pyi

The deprecated overload comes first and takes the deprecated form as a *required* argument, so that only
calls using it match, and the following overload is the real signature.
"""

import argparse
import importlib
import inspect
import sys
from typing import Any, Callable, List, Optional, Tuple

from ._decorator import (
    DeprecatedParameters,
    ParameterDeprecation,
    _rescued_positional,
    get_deprecated_parameters,
)

__all__ = [
    "generate_stub",
]

header = """# Generated by deprecated-parameters-stubgen for {module}, do not edit by hand.
# Add these overloads above the corresponding function in the module itself, or merge them into its
# stub file. Imports may need to be adjusted for the names used in the annotations.
import sys
from typing import Any, Literal, overload

if sys.version_info >= (3, 13):
    from warnings import deprecated
else:
    from typing_extensions import deprecated
"""


def _render_annotation(annotation: Any) -> Optional[str]:
    if annotation is inspect.Parameter.empty:
        return None
    if isinstance(annotation, str):
        return annotation
    return inspect.formatannotation(annotation)


def _render_parameter(param: inspect.Parameter, annotation: Optional[str] = None) -> str:
    rendered = param.name
    annotation = annotation if annotation is not None else _render_annotation(param.annotation)
    if annotation is not None:
        rendered += f": {annotation}"
    if param.default is not inspect.Parameter.empty:
        rendered += " = ..."
    return rendered


def _render_signature(params: List[inspect.Parameter], annotations: Optional[dict] = None) -> str:
    annotations = annotations or {}
    parts: List[str] = []
    previous_kind = None
    for param in params:
        if param.kind is inspect.Parameter.KEYWORD_ONLY and previous_kind not in (
            inspect.Parameter.KEYWORD_ONLY,
            inspect.Parameter.VAR_POSITIONAL,
        ):
            parts.append("*")
        if param.kind is inspect.Parameter.VAR_POSITIONAL:
            parts.append(f"*{_render_parameter(param, annotations.get(param.name))}")
        elif param.kind is inspect.Parameter.VAR_KEYWORD:
            parts.append(f"**{_render_parameter(param, annotations.get(param.name))}")
        else:
            parts.append(_render_parameter(param, annotations.get(param.name)))
        if param.kind is inspect.Parameter.POSITIONAL_ONLY:
            next_index = params.index(param) + 1
            if next_index == len(params) or params[next_index].kind is not inspect.Parameter.POSITIONAL_ONLY:
                parts.append("/")
        previous_kind = param.kind
    return ", ".join(parts)


def _required(param: inspect.Parameter, kind: Any = None, annotation: Any = None) -> inspect.Parameter:
    """Copy of a parameter that has no default, so that an overload only matches when it is given."""
    return param.replace(
        default=inspect.Parameter.empty,
        kind=kind if kind is not None else param.kind,
        annotation=annotation if annotation is not None else param.annotation,
    )


def _deprecated_variants(
    signature: inspect.Signature, deprecations: DeprecatedParameters
) -> List[Tuple[ParameterDeprecation, List[inspect.Parameter], dict]]:
    """One deprecated overload per deprecation: its message, parameters and annotation overrides."""
    variants: List[Tuple[ParameterDeprecation, List[inspect.Parameter], dict]] = []
    params = list(signature.parameters.values())

    for removal in deprecations.removed:
        if removal.old_name in signature.parameters:
            # Without a transform the parameter is still there, so the overload only makes it required.
            variant = [_required(p) if p.name == removal.old_name else p for p in params]
            variants.append((removal, variant, {}))
        else:
            extra = inspect.Parameter(removal.old_name, inspect.Parameter.KEYWORD_ONLY, annotation=Any)
            variants.append((removal, [*params, extra], {removal.old_name: "Any"}))

    for rename in deprecations.renamed:
        without_new = [p for p in params if p.name != rename.new_name]
        new_param = signature.parameters.get(rename.new_name)
        annotation = _render_annotation(new_param.annotation) if new_param else None
        old = inspect.Parameter(rename.old_name, inspect.Parameter.KEYWORD_ONLY, annotation=Any)
        variants.append((rename, [*without_new, old], {rename.old_name: annotation or "Any"}))

    # One overload per prefix of the parameters that a caller can still give at a position the signature
    # no longer has, whether they were removed or became keyword-only, since a caller may be giving only
    # the first of them. Every parameter up to the last one given positionally becomes positional-only
    # and required, so that only such calls match the overload.
    ordered = sorted([*deprecations.positional, *_rescued_positional(deprecations.removed)], key=lambda x: x.old_index)
    deprecated_names = [x.name for x in ordered]
    for count, deprecation in enumerate(ordered, start=1):
        prefix = deprecated_names[:count]
        leading = [
            _required(p, kind=inspect.Parameter.POSITIONAL_ONLY)
            for p in params
            if p.name not in deprecated_names
            if p.kind in (inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.POSITIONAL_OR_KEYWORD)
        ]
        # A removed parameter is no longer in the signature, so there is nothing to take its type from.
        promoted = [
            _required(signature.parameters[name], kind=inspect.Parameter.POSITIONAL_ONLY)
            if name in signature.parameters
            else inspect.Parameter(name, inspect.Parameter.POSITIONAL_ONLY, annotation=Any)
            for name in prefix
        ]
        rest = [
            p
            for p in params
            if p.name not in prefix
            and p.kind not in (inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.POSITIONAL_OR_KEYWORD)
        ]
        annotations = {name: "Any" for name in prefix if name not in signature.parameters}
        variants.append((deprecation, [*leading, *promoted, *rest], annotations))

    for value in deprecations.values:
        variant = [_required(p) if p.name == value.name else p for p in params]
        variants.append((value, variant, {value.name: f"Literal[{value.old_value!r}]"}))

    return variants


def _render_callable(name: str, func: Callable, deprecations: DeprecatedParameters, indent: str = "") -> str:
    signature = deprecations.signature or inspect.signature(func)
    returns = _render_annotation(signature.return_annotation)
    suffix = f" -> {returns}" if returns else ""
    lines = []
    for deprecation, params, annotations in _deprecated_variants(signature, deprecations):
        message = deprecation.format(name).replace('"', '\\"')
        lines.append(f"{indent}@overload")
        lines.append(f'{indent}@deprecated("{message}")')
        lines.append(f"{indent}def {name}({_render_signature(params, annotations)}){suffix}: ...")
    lines.append(f"{indent}@overload")
    lines.append(f"{indent}def {name}({_render_signature(list(signature.parameters.values()))}){suffix}: ...")
    return "\n".join(lines)


def generate_stub(module_name: str) -> str:
    """Render a stub with the deprecated overloads of every decorated callable in a module."""
    module = importlib.import_module(module_name)
    blocks = []

    for name, member in vars(module).items():
        if name.startswith("_"):
            continue
        deprecations = get_deprecated_parameters(member)
        if deprecations is not None and callable(member):
            blocks.append(_render_callable(name, member, deprecations))
        elif inspect.isclass(member) and member.__module__ == module_name:
            methods = []
            for method_name, method in vars(member).items():
                method_deprecations = get_deprecated_parameters(method)
                if method_deprecations is not None:
                    methods.append(_render_callable(method_name, method, method_deprecations, indent="    "))
            if methods:
                blocks.append(f"class {name}:\n" + "\n".join(methods))

    if not blocks:
        return ""
    return header.format(module=module_name) + "\n" + "\n\n".join(blocks) + "\n"


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="deprecated-parameters-stubgen",
        description=__doc__.split("\n")[0],
    )
    parser.add_argument("module", help="module to generate the stub for, e.g. mypackage.mymodule")
    parser.add_argument("-o", "--output", help="file to write to, defaults to standard output")
    args = parser.parse_args(argv)

    stub = generate_stub(args.module)
    if not stub:
        print(f"No deprecated parameters found in {args.module}.", file=sys.stderr)
        return 1
    if args.output:
        with open(args.output, "w") as handle:
            handle.write(stub)
    else:
        sys.stdout.write(stub)
    return 0


if __name__ == "__main__":
    sys.exit(main())
